name: remote_jukebox_32
description: "Playing song on an esp32 via qr codes"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Json part
  json_annotation: ^4.9.0

  # Icons part
  cupertino_icons: ^1.0.8

  # Shared Preferences
  shared_preferences: ^2.3.3

  # Provider
  provider: ^6.1.2

  # QR Code
  qr_flutter: ^4.1.0

  # Firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.0


dev_dependencies:
  # Flutter part
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Json part
  json_serializable: ^6.9.0

  # Build runner (for code generation)
  build_runner: ^2.4.13



# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700